#= require "jquery"
#= require "form"
#= require "footer"
#= require "header"
#= require "headroom.js/dist/headroom"
#= require "magnific-popup/dist/jquery.magnific-popup"
#= require "player"
#= require "history-api"
